// Emoji catalogue for the reaction picker and message composer.
// Generated from the Unicode character database: [emoji, searchable name].
// Any emoji NOT in this list can still be used — the picker has a
// "type any emoji" box that opens the device's own emoji keyboard.
export const EMOJI_CATEGORIES = [
  { id: "smileys", label: "Smileys", emoji: [
    ["☹️", "frowning face"],
    ["☺️", "smiling face"],
    ["😀", "grinning face"],
    ["😁", "grinning face with smiling eyes"],
    ["😂", "face with tears of joy"],
    ["😃", "smiling face with open mouth"],
    ["😄", "smiling face with open mouth and smiling eyes"],
    ["😅", "smiling face with open mouth and cold sweat"],
    ["😆", "smiling face with open mouth and tightly-closed eyes"],
    ["😇", "smiling face with halo"],
    ["😈", "smiling face with horns"],
    ["😉", "winking face"],
    ["😊", "smiling face with smiling eyes"],
    ["😋", "face savouring delicious food"],
    ["😌", "relieved face"],
    ["😍", "smiling face with heart-shaped eyes"],
    ["😎", "smiling face with sunglasses"],
    ["😏", "smirking face"],
    ["😐", "neutral face"],
    ["😑", "expressionless face"],
    ["😒", "unamused face"],
    ["😓", "face with cold sweat"],
    ["😔", "pensive face"],
    ["😕", "confused face"],
    ["😖", "confounded face"],
    ["😗", "kissing face"],
    ["😘", "face throwing a kiss"],
    ["😙", "kissing face with smiling eyes"],
    ["😚", "kissing face with closed eyes"],
    ["😛", "face with stuck-out tongue"],
    ["😜", "face with stuck-out tongue and winking eye"],
    ["😝", "face with stuck-out tongue and tightly-closed eyes"],
    ["😞", "disappointed face"],
    ["😟", "worried face"],
    ["😠", "angry face"],
    ["😡", "pouting face"],
    ["😢", "crying face"],
    ["😣", "persevering face"],
    ["😤", "face with look of triumph"],
    ["😥", "disappointed but relieved face"],
    ["😦", "frowning face with open mouth"],
    ["😧", "anguished face"],
    ["😨", "fearful face"],
    ["😩", "weary face"],
    ["😪", "sleepy face"],
    ["😫", "tired face"],
    ["😬", "grimacing face"],
    ["😭", "loudly crying face"],
    ["😮", "face with open mouth"],
    ["😯", "hushed face"],
    ["😰", "face with open mouth and cold sweat"],
    ["😱", "face screaming in fear"],
    ["😲", "astonished face"],
    ["😳", "flushed face"],
    ["😴", "sleeping face"],
    ["😵", "dizzy face"],
    ["😶", "face without mouth"],
    ["😷", "face with medical mask"],
    ["😸", "grinning cat face with smiling eyes"],
    ["😹", "cat face with tears of joy"],
    ["😺", "smiling cat face with open mouth"],
    ["😻", "smiling cat face with heart-shaped eyes"],
    ["😼", "cat face with wry smile"],
    ["😽", "kissing cat face with closed eyes"],
    ["😾", "pouting cat face"],
    ["😿", "crying cat face"],
    ["🙀", "weary cat face"],
    ["🙁", "slightly frowning face"],
    ["🙂", "slightly smiling face"],
    ["🙃", "upside-down face"],
    ["🙄", "face with rolling eyes"],
    ["🙅", "face with no good gesture"],
    ["🙆", "face with ok gesture"],
    ["🙇", "person bowing deeply"],
    ["🙈", "see-no-evil monkey"],
    ["🙉", "hear-no-evil monkey"],
    ["🙊", "speak-no-evil monkey"],
    ["🤐", "zipper-mouth face"],
    ["🤑", "money-mouth face"],
    ["🤒", "face with thermometer"],
    ["🤓", "nerd face"],
    ["🤔", "thinking face"],
    ["🤕", "face with head-bandage"],
    ["🤖", "robot face"],
    ["🤗", "hugging face"],
    ["🤘", "sign of the horns"],
    ["🤙", "call me hand"],
    ["🤚", "raised back of hand"],
    ["🤛", "left-facing fist"],
    ["🤜", "right-facing fist"],
    ["🤝", "handshake"],
    ["🤞", "hand with index and middle fingers crossed"],
    ["🤟", "i love you hand sign"],
    ["🤠", "face with cowboy hat"],
    ["🤡", "clown face"],
    ["🤢", "nauseated face"],
    ["🤣", "rolling on the floor laughing"],
    ["🤤", "drooling face"],
    ["🤥", "lying face"],
    ["🤦", "face palm"],
    ["🤧", "sneezing face"],
    ["🤨", "face with one eyebrow raised"],
    ["🤩", "grinning face with star eyes"],
    ["🤪", "grinning face with one large and one small eye"],
    ["🤫", "face with finger covering closed lips"],
    ["🤬", "serious face with symbols covering mouth"],
    ["🤭", "smiling face with smiling eyes and hand covering mouth"],
    ["🤮", "face with open mouth vomiting"],
    ["🤯", "shocked face with exploding head"],
    ["🥰", "smiling face with smiling eyes and three hearts"],
    ["🥱", "yawning face"],
    ["🥲", "smiling face with tear"],
    ["🥳", "face with party horn and party hat"],
    ["🥴", "face with uneven eyes and wavy mouth"],
    ["🥵", "overheated face"],
    ["🥶", "freezing face"],
    ["🥷", "ninja"],
    ["🥸", "disguised face"],
    ["🥹", "face holding back tears"],
    ["🥺", "face with pleading eyes"],
    ["🥻", "sari"],
    ["🥼", "lab coat"],
    ["🥽", "goggles"],
    ["🥾", "hiking boot"],
    ["🥿", "flat shoe"],
    ["🫠", "melting face"],
    ["🫡", "saluting face"],
    ["🫢", "face with open eyes and hand over mouth"],
    ["🫣", "face with peeking eye"],
    ["🫤", "face with diagonal mouth"],
    ["🫥", "dotted line face"],
    ["🫦", "biting lip"],
    ["🫧", "bubbles"],
    ["🫨", "shaking face"]
  ] },
  { id: "people", label: "People & gestures", emoji: [
    ["✍️", "writing hand"],
    ["☝️", "index pointing up"],
    ["✌️", "victory hand peace"],
    ["🙋", "happy person raising one hand"],
    ["🙌", "person raising both hands in celebration"],
    ["🙍", "person frowning"],
    ["🙎", "person with pouting face"],
    ["🙏", "person with folded hands"],
    ["🤰", "pregnant woman"],
    ["🤱", "breast-feeding"],
    ["🤲", "palms up together"],
    ["🤳", "selfie"],
    ["🤴", "prince"],
    ["🤵", "man in tuxedo"],
    ["🤶", "mother christmas"],
    ["🤷", "shrug"],
    ["🤸", "person doing cartwheel"],
    ["🤹", "juggling"],
    ["🤺", "fencer"],
    ["🤼", "wrestlers"],
    ["🤽", "water polo"],
    ["🤾", "handball"],
    ["🤿", "diving mask"],
    ["🦰", "emoji component red hair"],
    ["🦱", "emoji component curly hair"],
    ["🦲", "emoji component bald"],
    ["🦳", "emoji component white hair"],
    ["🦴", "bone"],
    ["🦵", "leg"],
    ["🦶", "foot"],
    ["🦷", "tooth"],
    ["🦸", "superhero"],
    ["🦹", "supervillain"],
    ["🦺", "safety vest"],
    ["🦻", "ear with hearing aid"],
    ["🦼", "motorized wheelchair"],
    ["🦽", "manual wheelchair"],
    ["🦾", "mechanical arm"],
    ["🦿", "mechanical leg"],
    ["🧐", "face with monocle"],
    ["🧑", "adult"],
    ["🧒", "child"],
    ["🧓", "older adult"],
    ["🧔", "bearded person"],
    ["🧕", "person with headscarf"],
    ["🧖", "person in steamy room"],
    ["🧗", "person climbing"],
    ["🧘", "person in lotus position"],
    ["🧙", "mage"],
    ["🧚", "fairy"],
    ["🧛", "vampire"],
    ["🧜", "merperson"],
    ["🧝", "elf"],
    ["🧞", "genie"],
    ["🧟", "zombie"],
    ["🫰", "hand with index finger and thumb crossed"],
    ["🫱", "rightwards hand"],
    ["🫲", "leftwards hand"],
    ["🫳", "palm down hand"],
    ["🫴", "palm up hand"],
    ["🫵", "index pointing at the viewer"],
    ["🫶", "heart hands"],
    ["🫷", "leftwards pushing hand"],
    ["🫸", "rightwards pushing hand"],
    ["👀", "eyes"],
    ["👂", "ear"],
    ["👃", "nose"],
    ["👄", "mouth"],
    ["👅", "tongue"],
    ["👆", "white up pointing backhand index"],
    ["👇", "white down pointing backhand index"],
    ["👈", "white left pointing backhand index"],
    ["👉", "white right pointing backhand index"],
    ["👊", "fisted hand sign"],
    ["👋", "waving hand sign"],
    ["👌", "ok hand sign"],
    ["👍", "thumbs up sign"],
    ["👎", "thumbs down sign"],
    ["👏", "clapping hands sign"],
    ["👐", "open hands sign"],
    ["👦", "boy"],
    ["👧", "girl"],
    ["👨", "man"],
    ["👩", "woman"],
    ["👪", "family"],
    ["👫", "man and woman holding hands"],
    ["👬", "two men holding hands"],
    ["👭", "two women holding hands"],
    ["👮", "police officer"],
    ["👯", "woman with bunny ears"],
    ["👰", "bride with veil"],
    ["👱", "person with blond hair"],
    ["👲", "man with gua pi mao"],
    ["👳", "man with turban"],
    ["👴", "older man"],
    ["👵", "older woman"],
    ["👶", "baby"],
    ["👷", "construction worker"],
    ["👸", "princess"],
    ["👹", "japanese ogre"],
    ["👺", "japanese goblin"],
    ["👻", "ghost"],
    ["👼", "baby angel"],
    ["👽", "extraterrestrial alien"],
    ["👾", "alien monster"],
    ["👿", "imp"],
    ["💀", "skull"],
    ["💁", "information desk person"],
    ["💂", "guardsman"],
    ["💃", "dancer"],
    ["💄", "lipstick"],
    ["💅", "nail polish"],
    ["💆", "face massage"],
    ["💇", "haircut"],
    ["💪", "flexed biceps"],
    ["✊", "raised fist"],
    ["✋", "raised hand"]
  ] },
  { id: "hearts", label: "Hearts & feelings", emoji: [
    ["❤️", "red heart"],
    ["🩵", "light blue heart"],
    ["🩶", "grey heart"],
    ["🩷", "pink heart"],
    ["💓", "beating heart"],
    ["💔", "broken heart"],
    ["💕", "two hearts"],
    ["💖", "sparkling heart"],
    ["💗", "growing heart"],
    ["💘", "heart with arrow"],
    ["💙", "blue heart"],
    ["💚", "green heart"],
    ["💛", "yellow heart"],
    ["💜", "purple heart"],
    ["💝", "heart with ribbon"],
    ["💞", "revolving hearts"],
    ["💟", "heart decoration"],
    ["💢", "anger symbol"],
    ["💣", "bomb"],
    ["💤", "sleeping symbol"],
    ["💥", "collision symbol"],
    ["💦", "splashing sweat symbol"],
    ["💧", "droplet"],
    ["💨", "dash symbol"],
    ["💩", "pile of poo"],
    ["💫", "dizzy symbol"],
    ["💬", "speech balloon"],
    ["💭", "thought balloon"],
    ["💮", "white flower"],
    ["💯", "hundred points symbol"]
  ] },
  { id: "nature", label: "Animals & nature", emoji: [
    ["🦀", "crab"],
    ["🦁", "lion face"],
    ["🦂", "scorpion"],
    ["🦃", "turkey"],
    ["🦄", "unicorn face"],
    ["🦅", "eagle"],
    ["🦆", "duck"],
    ["🦇", "bat"],
    ["🦈", "shark"],
    ["🦉", "owl"],
    ["🦊", "fox face"],
    ["🦋", "butterfly"],
    ["🦌", "deer"],
    ["🦍", "gorilla"],
    ["🦎", "lizard"],
    ["🦏", "rhinoceros"],
    ["🦐", "shrimp"],
    ["🦑", "squid"],
    ["🦒", "giraffe face"],
    ["🦓", "zebra face"],
    ["🦔", "hedgehog"],
    ["🦕", "sauropod"],
    ["🦖", "t-rex"],
    ["🦗", "cricket"],
    ["🦘", "kangaroo"],
    ["🦙", "llama"],
    ["🦚", "peacock"],
    ["🦛", "hippopotamus"],
    ["🦜", "parrot"],
    ["🦝", "raccoon"],
    ["🦞", "lobster"],
    ["🦟", "mosquito"],
    ["🦠", "microbe"],
    ["🦡", "badger"],
    ["🦢", "swan"],
    ["🦣", "mammoth"],
    ["🦤", "dodo"],
    ["🦥", "sloth"],
    ["🦦", "otter"],
    ["🦧", "orangutan"],
    ["🦨", "skunk"],
    ["🦩", "flamingo"],
    ["🦪", "oyster"],
    ["🦫", "beaver"],
    ["🦬", "bison"],
    ["🦭", "seal"],
    ["🦮", "guide dog"],
    ["🦯", "probing cane"],
    ["🪰", "fly"],
    ["🪱", "worm"],
    ["🪲", "beetle"],
    ["🪳", "cockroach"],
    ["🪴", "potted plant"],
    ["🪵", "wood"],
    ["🪶", "feather"],
    ["🪷", "lotus"],
    ["🪸", "coral"],
    ["🪹", "empty nest"],
    ["🪺", "nest with eggs"],
    ["🪻", "hyacinth"],
    ["🪼", "jellyfish"],
    ["🪽", "wing"],
    ["🪿", "goose"],
    ["🌰", "chestnut"],
    ["🌱", "seedling"],
    ["🌲", "evergreen tree"],
    ["🌳", "deciduous tree"],
    ["🌴", "palm tree"],
    ["🌵", "cactus"],
    ["🌷", "tulip"],
    ["🌸", "cherry blossom"],
    ["🌹", "rose"],
    ["🌺", "hibiscus"],
    ["🌻", "sunflower"],
    ["🌼", "blossom"],
    ["🌽", "ear of maize"],
    ["🌾", "ear of rice"],
    ["🌿", "herb"],
    ["🍀", "four leaf clover"],
    ["🍁", "maple leaf"],
    ["🍂", "fallen leaf"],
    ["🍃", "leaf fluttering in wind"],
    ["🍄", "mushroom"],
    ["🐀", "rat"],
    ["🐁", "mouse"],
    ["🐂", "ox"],
    ["🐃", "water buffalo"],
    ["🐄", "cow"],
    ["🐅", "tiger"],
    ["🐆", "leopard"],
    ["🐇", "rabbit"],
    ["🐈", "cat"],
    ["🐉", "dragon"],
    ["🐊", "crocodile"],
    ["🐋", "whale"],
    ["🐌", "snail"],
    ["🐍", "snake"],
    ["🐎", "horse"],
    ["🐏", "ram"],
    ["🐐", "goat"],
    ["🐑", "sheep"],
    ["🐒", "monkey"],
    ["🐓", "rooster"],
    ["🐔", "chicken"],
    ["🐕", "dog"],
    ["🐖", "pig"],
    ["🐗", "boar"],
    ["🐘", "elephant"],
    ["🐙", "octopus"],
    ["🐚", "spiral shell"],
    ["🐛", "bug"],
    ["🐜", "ant"],
    ["🐝", "honeybee"],
    ["🐞", "lady beetle"],
    ["🐟", "fish"],
    ["🐠", "tropical fish"],
    ["🐡", "blowfish"],
    ["🐢", "turtle"],
    ["🐣", "hatching chick"],
    ["🐤", "baby chick"],
    ["🐥", "front-facing baby chick"],
    ["🐦", "bird"],
    ["🐧", "penguin"],
    ["🐨", "koala"],
    ["🐩", "poodle"],
    ["🐪", "dromedary camel"],
    ["🐫", "bactrian camel"],
    ["🐬", "dolphin"],
    ["🐭", "mouse face"],
    ["🐮", "cow face"],
    ["🐯", "tiger face"],
    ["🐰", "rabbit face"],
    ["🐱", "cat face"],
    ["🐲", "dragon face"],
    ["🐳", "spouting whale"],
    ["🐴", "horse face"],
    ["🐵", "monkey face"],
    ["🐶", "dog face"],
    ["🐷", "pig face"],
    ["🐸", "frog face"],
    ["🐹", "hamster face"],
    ["🐺", "wolf face"],
    ["🐻", "bear face"],
    ["🐼", "panda face"],
    ["🐽", "pig nose"],
    ["🐾", "paw prints"]
  ] },
  { id: "food", label: "Food & drink", emoji: [
    ["🥐", "croissant"],
    ["🥑", "avocado"],
    ["🥒", "cucumber"],
    ["🥓", "bacon"],
    ["🥔", "potato"],
    ["🥕", "carrot"],
    ["🥖", "baguette bread"],
    ["🥗", "green salad"],
    ["🥘", "shallow pan of food"],
    ["🥙", "stuffed flatbread"],
    ["🥚", "egg"],
    ["🥛", "glass of milk"],
    ["🥜", "peanuts"],
    ["🥝", "kiwifruit"],
    ["🥞", "pancakes"],
    ["🥟", "dumpling"],
    ["🥠", "fortune cookie"],
    ["🥡", "takeout box"],
    ["🥢", "chopsticks"],
    ["🥣", "bowl with spoon"],
    ["🥤", "cup with straw"],
    ["🥥", "coconut"],
    ["🥦", "broccoli"],
    ["🥧", "pie"],
    ["🥨", "pretzel"],
    ["🥩", "cut of meat"],
    ["🥪", "sandwich"],
    ["🥫", "canned food"],
    ["🥬", "leafy green"],
    ["🥭", "mango"],
    ["🥮", "moon cake"],
    ["🥯", "bagel"],
    ["🧀", "cheese wedge"],
    ["🧁", "cupcake"],
    ["🧂", "salt shaker"],
    ["🧃", "beverage box"],
    ["🧄", "garlic"],
    ["🧅", "onion"],
    ["🧆", "falafel"],
    ["🧇", "waffle"],
    ["🧈", "butter"],
    ["🧉", "mate drink"],
    ["🧊", "ice cube"],
    ["🧋", "bubble tea"],
    ["🫐", "blueberries"],
    ["🫑", "bell pepper"],
    ["🫒", "olive"],
    ["🫓", "flatbread"],
    ["🫔", "tamale"],
    ["🫕", "fondue"],
    ["🫖", "teapot"],
    ["🫗", "pouring liquid"],
    ["🫘", "beans"],
    ["🫙", "jar"],
    ["🫚", "ginger root"],
    ["🫛", "pea pod"],
    ["🍅", "tomato"],
    ["🍆", "aubergine"],
    ["🍇", "grapes"],
    ["🍈", "melon"],
    ["🍉", "watermelon"],
    ["🍊", "tangerine"],
    ["🍋", "lemon"],
    ["🍌", "banana"],
    ["🍍", "pineapple"],
    ["🍎", "red apple"],
    ["🍏", "green apple"],
    ["🍐", "pear"],
    ["🍑", "peach"],
    ["🍒", "cherries"],
    ["🍓", "strawberry"],
    ["🍔", "hamburger"],
    ["🍕", "slice of pizza"],
    ["🍖", "meat on bone"],
    ["🍗", "poultry leg"],
    ["🍘", "rice cracker"],
    ["🍙", "rice ball"],
    ["🍚", "cooked rice"],
    ["🍛", "curry and rice"],
    ["🍜", "steaming bowl"],
    ["🍝", "spaghetti"],
    ["🍞", "bread"],
    ["🍟", "french fries"],
    ["🍠", "roasted sweet potato"],
    ["🍡", "dango"],
    ["🍢", "oden"],
    ["🍣", "sushi"],
    ["🍤", "fried shrimp"],
    ["🍥", "fish cake with swirl design"],
    ["🍦", "soft ice cream"],
    ["🍧", "shaved ice"],
    ["🍨", "ice cream"],
    ["🍩", "doughnut"],
    ["🍪", "cookie"],
    ["🍫", "chocolate bar"],
    ["🍬", "candy"],
    ["🍭", "lollipop"],
    ["🍮", "custard"],
    ["🍯", "honey pot"],
    ["🍰", "shortcake"],
    ["🍱", "bento box"],
    ["🍲", "pot of food"],
    ["🍳", "cooking"],
    ["🍴", "fork and knife"],
    ["🍵", "teacup without handle"],
    ["🍶", "sake bottle and cup"],
    ["🍷", "wine glass"],
    ["🍸", "cocktail glass"],
    ["🍹", "tropical drink"],
    ["🍺", "beer mug"],
    ["🍻", "clinking beer mugs"],
    ["🍼", "baby bottle"]
  ] },
  { id: "activities", label: "Activities", emoji: [
    ["🥅", "goal net"],
    ["🥇", "first place medal"],
    ["🥈", "second place medal"],
    ["🥉", "third place medal"],
    ["🥊", "boxing glove"],
    ["🥋", "martial arts uniform"],
    ["🥌", "curling stone"],
    ["🥍", "lacrosse stick and ball"],
    ["🥎", "softball"],
    ["🥏", "flying disc"],
    ["🎀", "ribbon"],
    ["🎁", "wrapped present"],
    ["🎂", "birthday cake"],
    ["🎃", "jack-o-lantern"],
    ["🎄", "christmas tree"],
    ["🎅", "father christmas"],
    ["🎆", "fireworks"],
    ["🎇", "firework sparkler"],
    ["🎈", "balloon"],
    ["🎉", "party popper"],
    ["🎊", "confetti ball"],
    ["🎋", "tanabata tree"],
    ["🎌", "crossed flags"],
    ["🎍", "pine decoration"],
    ["🎎", "japanese dolls"],
    ["🎏", "carp streamer"],
    ["🎐", "wind chime"],
    ["🎑", "moon viewing ceremony"],
    ["🎒", "school satchel"],
    ["🎓", "graduation cap"],
    ["🎠", "carousel horse"],
    ["🎡", "ferris wheel"],
    ["🎢", "roller coaster"],
    ["🎣", "fishing pole and fish"],
    ["🎤", "microphone"],
    ["🎥", "movie camera"],
    ["🎦", "cinema"],
    ["🎧", "headphone"],
    ["🎨", "artist palette"],
    ["🎩", "top hat"],
    ["🎪", "circus tent"],
    ["🎫", "ticket"],
    ["🎬", "clapper board"],
    ["🎭", "performing arts"],
    ["🎮", "video game"],
    ["🎯", "direct hit"],
    ["🎰", "slot machine"],
    ["🎱", "billiards"],
    ["🎲", "game die"],
    ["🎳", "bowling"],
    ["🎴", "flower playing cards"],
    ["🎵", "musical note"],
    ["🎶", "multiple musical notes"],
    ["🎷", "saxophone"],
    ["🎸", "guitar"],
    ["🎹", "musical keyboard"],
    ["🎺", "trumpet"],
    ["🎻", "violin"],
    ["🎼", "musical score"],
    ["🎽", "running shirt with sash"],
    ["🎾", "tennis racquet and ball"],
    ["🎿", "ski and ski boot"],
    ["🏀", "basketball and hoop"],
    ["🏁", "chequered flag"],
    ["🏂", "snowboarder"],
    ["🏃", "runner"],
    ["🏄", "surfer"],
    ["🏅", "sports medal"],
    ["🏆", "trophy"],
    ["🏇", "horse racing"],
    ["🏈", "american football"],
    ["🏉", "rugby football"],
    ["🏊", "swimmer"],
    ["🏏", "cricket bat and ball"],
    ["🏐", "volleyball"],
    ["🏑", "field hockey stick and ball"],
    ["🏒", "ice hockey stick and puck"],
    ["🏓", "table tennis paddle and ball"]
  ] },
  { id: "travel", label: "Travel & weather", emoji: [
    ["✈️", "airplane"],
    ["❄️", "snowflake"],
    ["☀️", "sun sunny"],
    ["🌀", "cyclone"],
    ["🌁", "foggy"],
    ["🌂", "closed umbrella"],
    ["🌃", "night with stars"],
    ["🌄", "sunrise over mountains"],
    ["🌅", "sunrise"],
    ["🌆", "cityscape at dusk"],
    ["🌇", "sunset over buildings"],
    ["🌈", "rainbow"],
    ["🌉", "bridge at night"],
    ["🌊", "water wave"],
    ["🌋", "volcano"],
    ["🌌", "milky way"],
    ["🌍", "earth globe europe-africa"],
    ["🌎", "earth globe americas"],
    ["🌏", "earth globe asia-australia"],
    ["🌐", "globe with meridians"],
    ["🌑", "new moon symbol"],
    ["🌒", "waxing crescent moon symbol"],
    ["🌓", "first quarter moon symbol"],
    ["🌔", "waxing gibbous moon symbol"],
    ["🌕", "full moon symbol"],
    ["🌖", "waning gibbous moon symbol"],
    ["🌗", "last quarter moon symbol"],
    ["🌘", "waning crescent moon symbol"],
    ["🌙", "crescent moon"],
    ["🌚", "new moon with face"],
    ["🌛", "first quarter moon with face"],
    ["🌜", "last quarter moon with face"],
    ["🌝", "full moon with face"],
    ["🌞", "sun with face"],
    ["🌟", "glowing star"],
    ["🌠", "shooting star"],
    ["🏠", "house building"],
    ["🏡", "house with garden"],
    ["🏢", "office building"],
    ["🏣", "japanese post office"],
    ["🏤", "european post office"],
    ["🏥", "hospital"],
    ["🏦", "bank"],
    ["🏧", "automated teller machine"],
    ["🏨", "hotel"],
    ["🏩", "love hotel"],
    ["🏪", "convenience store"],
    ["🏫", "school"],
    ["🏬", "department store"],
    ["🏭", "factory"],
    ["🏮", "izakaya lantern"],
    ["🏯", "japanese castle"],
    ["🏰", "european castle"],
    ["🚀", "rocket"],
    ["🚁", "helicopter"],
    ["🚂", "steam locomotive"],
    ["🚃", "railway car"],
    ["🚄", "high-speed train"],
    ["🚅", "high-speed train with bullet nose"],
    ["🚆", "train"],
    ["🚇", "metro"],
    ["🚈", "light rail"],
    ["🚉", "station"],
    ["🚊", "tram"],
    ["🚋", "tram car"],
    ["🚌", "bus"],
    ["🚍", "oncoming bus"],
    ["🚎", "trolleybus"],
    ["🚏", "bus stop"],
    ["🚐", "minibus"],
    ["🚑", "ambulance"],
    ["🚒", "fire engine"],
    ["🚓", "police car"],
    ["🚔", "oncoming police car"],
    ["🚕", "taxi"],
    ["🚖", "oncoming taxi"],
    ["🚗", "automobile"],
    ["🚘", "oncoming automobile"],
    ["🚙", "recreational vehicle"],
    ["🚚", "delivery truck"],
    ["🚛", "articulated lorry"],
    ["🚜", "tractor"],
    ["🚝", "monorail"],
    ["🚞", "mountain railway"],
    ["🚟", "suspension railway"],
    ["🚠", "mountain cableway"],
    ["🚡", "aerial tramway"],
    ["🚢", "ship"],
    ["🚣", "rowboat"],
    ["🚤", "speedboat"],
    ["🚥", "horizontal traffic light"],
    ["🚦", "vertical traffic light"],
    ["🚧", "construction sign"],
    ["🚨", "police cars revolving light"],
    ["🚩", "triangular flag on post"],
    ["🚪", "door"],
    ["🚫", "no entry sign"],
    ["🚬", "smoking symbol"],
    ["🚭", "no smoking symbol"],
    ["🚮", "put litter in its place symbol"],
    ["🚯", "do not litter symbol"],
    ["🚰", "potable water symbol"],
    ["🚱", "non-potable water symbol"],
    ["🚲", "bicycle"],
    ["🚳", "no bicycles"],
    ["🚴", "bicyclist"],
    ["🚵", "mountain bicyclist"],
    ["🚶", "pedestrian"],
    ["🚷", "no pedestrians"],
    ["🚸", "children crossing"],
    ["🚹", "mens symbol"],
    ["🚺", "womens symbol"],
    ["🚻", "restroom"],
    ["🚼", "baby symbol"],
    ["🚽", "toilet"],
    ["🚾", "water closet"],
    ["🚿", "shower"],
    ["🛀", "bath"],
    ["🛁", "bathtub"],
    ["🛂", "passport control"],
    ["🛃", "customs"],
    ["🛄", "baggage claim"],
    ["🛅", "left luggage"],
    ["🛌", "sleeping accommodation"],
    ["🛐", "place of worship"],
    ["🛑", "octagonal sign"],
    ["🛒", "shopping trolley"],
    ["🛕", "hindu temple"],
    ["🛖", "hut"],
    ["🛗", "elevator"],
    ["🛜", "wireless"],
    ["🛝", "playground slide"],
    ["🛞", "wheel"],
    ["🛟", "ring buoy"],
    ["🛫", "airplane departure"],
    ["🛬", "airplane arriving"],
    ["🛴", "scooter"],
    ["🛵", "motor scooter"],
    ["🛶", "canoe"],
    ["🛷", "sled"],
    ["🛸", "flying saucer"],
    ["🛹", "skateboard"],
    ["🛺", "auto rickshaw"],
    ["🛻", "pickup truck"],
    ["🛼", "roller skate"],
    ["☔", "umbrella with rain drops"],
    ["☕", "hot beverage"],
    ["♈", "aries"],
    ["♉", "taurus"],
    ["♊", "gemini"],
    ["♋", "cancer"],
    ["♌", "leo"],
    ["♍", "virgo"],
    ["♎", "libra"],
    ["♏", "scorpius"],
    ["♐", "sagittarius"],
    ["♑", "capricorn"],
    ["♒", "aquarius"],
    ["♓", "pisces"],
    ["♿", "wheelchair symbol"],
    ["⚓", "anchor"],
    ["⚡", "high voltage sign"],
    ["⚪", "medium white circle"],
    ["⚫", "medium black circle"],
    ["⚽", "soccer ball"],
    ["⚾", "baseball"],
    ["⛄", "snowman without snow"],
    ["⛅", "sun behind cloud"],
    ["⛎", "ophiuchus"],
    ["⛔", "no entry"],
    ["⛪", "church"],
    ["⛲", "fountain"],
    ["⛳", "flag in hole"],
    ["⛵", "sailboat"],
    ["⛺", "tent"],
    ["⛽", "fuel pump"]
  ] },
  { id: "objects", label: "Objects", emoji: [
    ["⌛", "hourglass"],
    ["☎️", "telephone"],
    ["✏️", "pencil"],
    ["✂️", "scissors"],
    ["🧠", "brain"],
    ["🧡", "orange heart"],
    ["🧢", "billed cap"],
    ["🧣", "scarf"],
    ["🧤", "gloves"],
    ["🧥", "coat"],
    ["🧦", "socks"],
    ["🧧", "red gift envelope"],
    ["🧨", "firecracker"],
    ["🧩", "jigsaw puzzle piece"],
    ["🧪", "test tube"],
    ["🧫", "petri dish"],
    ["🧬", "dna double helix"],
    ["🧭", "compass"],
    ["🧮", "abacus"],
    ["🧯", "fire extinguisher"],
    ["🧰", "toolbox"],
    ["🧱", "brick"],
    ["🧲", "magnet"],
    ["🧳", "luggage"],
    ["🧴", "lotion bottle"],
    ["🧵", "spool of thread"],
    ["🧶", "ball of yarn"],
    ["🧷", "safety pin"],
    ["🧸", "teddy bear"],
    ["🧹", "broom"],
    ["🧺", "basket"],
    ["🧻", "roll of paper"],
    ["🧼", "bar of soap"],
    ["🧽", "sponge"],
    ["🧾", "receipt"],
    ["🧿", "nazar amulet"],
    ["🩰", "ballet shoes"],
    ["🩱", "one-piece swimsuit"],
    ["🩲", "briefs"],
    ["🩳", "shorts"],
    ["🩴", "thong sandal"],
    ["🩸", "drop of blood"],
    ["🩹", "adhesive bandage"],
    ["🩺", "stethoscope"],
    ["🩻", "x-ray"],
    ["🩼", "crutch"],
    ["💠", "diamond shape with a dot inside"],
    ["💡", "electric light bulb"],
    ["💰", "money bag"],
    ["💱", "currency exchange"],
    ["💲", "heavy dollar sign"],
    ["💳", "credit card"],
    ["💴", "banknote with yen sign"],
    ["💵", "banknote with dollar sign"],
    ["💶", "banknote with euro sign"],
    ["💷", "banknote with pound sign"],
    ["💸", "money with wings"],
    ["💹", "chart with upwards trend and yen sign"],
    ["💺", "seat"],
    ["💻", "personal computer"],
    ["💼", "briefcase"],
    ["💽", "minidisc"],
    ["💾", "floppy disk"],
    ["💿", "optical disc"],
    ["📀", "dvd"],
    ["📁", "file folder"],
    ["📂", "open file folder"],
    ["📃", "page with curl"],
    ["📄", "page facing up"],
    ["📅", "calendar"],
    ["📆", "tear-off calendar"],
    ["📇", "card index"],
    ["📈", "chart with upwards trend"],
    ["📉", "chart with downwards trend"],
    ["📊", "bar chart"],
    ["📋", "clipboard"],
    ["📌", "pushpin"],
    ["📍", "round pushpin"],
    ["📎", "paperclip"],
    ["📏", "straight ruler"],
    ["📐", "triangular ruler"],
    ["📑", "bookmark tabs"],
    ["📒", "ledger"],
    ["📓", "notebook"],
    ["📔", "notebook with decorative cover"],
    ["📕", "closed book"],
    ["📖", "open book"],
    ["📗", "green book"],
    ["📘", "blue book"],
    ["📙", "orange book"],
    ["📚", "books"],
    ["📛", "name badge"],
    ["📜", "scroll"],
    ["📝", "memo"],
    ["📞", "telephone receiver"],
    ["📟", "pager"],
    ["📠", "fax machine"],
    ["📡", "satellite antenna"],
    ["📢", "public address loudspeaker"],
    ["📣", "cheering megaphone"],
    ["📤", "outbox tray"],
    ["📥", "inbox tray"],
    ["📦", "package"],
    ["📧", "e-mail symbol"],
    ["📨", "incoming envelope"],
    ["📩", "envelope with downwards arrow above"],
    ["📪", "closed mailbox with lowered flag"],
    ["📫", "closed mailbox with raised flag"],
    ["📬", "open mailbox with raised flag"],
    ["📭", "open mailbox with lowered flag"],
    ["📮", "postbox"],
    ["📯", "postal horn"],
    ["📰", "newspaper"],
    ["📱", "mobile phone"],
    ["📲", "mobile phone with rightwards arrow at left"],
    ["📳", "vibration mode"],
    ["📴", "mobile phone off"],
    ["📵", "no mobile phones"],
    ["📶", "antenna with bars"],
    ["📷", "camera"],
    ["📸", "camera with flash"],
    ["📹", "video camera"],
    ["📺", "television"],
    ["📻", "radio"],
    ["📼", "videocassette"],
    ["🔀", "twisted rightwards arrows"],
    ["🔁", "clockwise rightwards and leftwards open circle arrows"],
    ["🔂", "clockwise rightwards and leftwards open circle arrows with circled one overlay"],
    ["🔃", "clockwise downwards and upwards open circle arrows"],
    ["🔄", "anticlockwise downwards and upwards open circle arrows"],
    ["🔅", "low brightness symbol"],
    ["🔆", "high brightness symbol"],
    ["🔇", "speaker with cancellation stroke"],
    ["🔈", "speaker"],
    ["🔉", "speaker with one sound wave"],
    ["🔊", "speaker with three sound waves"],
    ["🔋", "battery"],
    ["🔌", "electric plug"],
    ["🔍", "left-pointing magnifying glass"],
    ["🔎", "right-pointing magnifying glass"],
    ["🔏", "lock with ink pen"],
    ["🔐", "closed lock with key"],
    ["🔑", "key"],
    ["🔒", "lock"],
    ["🔓", "open lock"],
    ["🔔", "bell"],
    ["🔕", "bell with cancellation stroke"],
    ["🔖", "bookmark"],
    ["🔗", "link symbol"],
    ["🔘", "radio button"],
    ["🔙", "back with leftwards arrow above"],
    ["🔚", "end with leftwards arrow above"],
    ["🔛", "on with exclamation mark with left right arrow above"],
    ["🔜", "soon with rightwards arrow above"],
    ["🔝", "top with upwards arrow above"],
    ["🔞", "no one under eighteen symbol"],
    ["🔟", "keycap ten"],
    ["🔠", "input symbol for latin capital letters"],
    ["🔡", "input symbol for latin small letters"],
    ["🔢", "input symbol for numbers"],
    ["🔣", "input symbol for symbols"],
    ["🔤", "input symbol for latin letters"],
    ["🔥", "fire"],
    ["🔦", "electric torch"],
    ["🔧", "wrench"],
    ["🔨", "hammer"],
    ["🔩", "nut and bolt"],
    ["🔪", "hocho"],
    ["🔫", "pistol"],
    ["🔬", "microscope"],
    ["🔭", "telescope"],
    ["🔮", "crystal ball"],
    ["🔯", "six pointed star with middle dot"],
    ["🔰", "japanese symbol for beginner"],
    ["🔱", "trident emblem"],
    ["🔲", "black square button"],
    ["🔳", "white square button"],
    ["🔴", "large red circle"],
    ["🔵", "large blue circle"],
    ["🔶", "large orange diamond"],
    ["🔷", "large blue diamond"],
    ["🔸", "small orange diamond"],
    ["🔹", "small blue diamond"],
    ["🔺", "up-pointing red triangle"],
    ["🔻", "down-pointing red triangle"],
    ["🔼", "up-pointing small red triangle"],
    ["🔽", "down-pointing small red triangle"],
    ["🕐", "clock face one oclock"],
    ["🕑", "clock face two oclock"],
    ["🕒", "clock face three oclock"],
    ["🕓", "clock face four oclock"],
    ["🕔", "clock face five oclock"],
    ["🕕", "clock face six oclock"],
    ["🕖", "clock face seven oclock"],
    ["🕗", "clock face eight oclock"],
    ["🕘", "clock face nine oclock"],
    ["🕙", "clock face ten oclock"],
    ["🕚", "clock face eleven oclock"],
    ["🕛", "clock face twelve oclock"],
    ["🕜", "clock face one-thirty"],
    ["🕝", "clock face two-thirty"],
    ["🕞", "clock face three-thirty"],
    ["🕟", "clock face four-thirty"],
    ["🕠", "clock face five-thirty"],
    ["🕡", "clock face six-thirty"],
    ["🕢", "clock face seven-thirty"],
    ["🕣", "clock face eight-thirty"],
    ["🕤", "clock face nine-thirty"],
    ["🕥", "clock face ten-thirty"],
    ["🕦", "clock face eleven-thirty"],
    ["🕧", "clock face twelve-thirty"]
  ] },
  { id: "symbols", label: "Symbols", emoji: [
    ["™️", "trade mark"],
    ["♻️", "recycle"],
    ["❣️", "heart exclamation"],
    ["⚠️", "warning"],
    ["✖️", "multiplication x"],
    ["✔️", "check mark done"],
    ["🥀", "wilted flower"],
    ["🥁", "drum with drumsticks"],
    ["🥂", "clinking glasses"],
    ["🥃", "tumbler glass"],
    ["🥄", "spoon"],
    ["🧌", "troll"],
    ["🧍", "standing person"],
    ["🧎", "kneeling person"],
    ["🧏", "deaf person"],
    ["🪀", "yo-yo"],
    ["🪁", "kite"],
    ["🪂", "parachute"],
    ["🪃", "boomerang"],
    ["🪄", "magic wand"],
    ["🪅", "pinata"],
    ["🪆", "nesting dolls"],
    ["🪇", "maracas"],
    ["🪈", "flute"],
    ["🪐", "ringed planet"],
    ["🪑", "chair"],
    ["🪒", "razor"],
    ["🪓", "axe"],
    ["🪔", "diya lamp"],
    ["🪕", "banjo"],
    ["🪖", "military helmet"],
    ["🪗", "accordion"],
    ["🪘", "long drum"],
    ["🪙", "coin"],
    ["🪚", "carpentry saw"],
    ["🪛", "screwdriver"],
    ["🪜", "ladder"],
    ["🪝", "hook"],
    ["🪞", "mirror"],
    ["🪟", "window"],
    ["🪠", "plunger"],
    ["🪡", "sewing needle"],
    ["🪢", "knot"],
    ["🪣", "bucket"],
    ["🪤", "mouse trap"],
    ["🪥", "toothbrush"],
    ["🪦", "headstone"],
    ["🪧", "placard"],
    ["🪨", "rock"],
    ["🪩", "mirror ball"],
    ["🪪", "identification card"],
    ["🪫", "low battery"],
    ["🪬", "hamsa"],
    ["🪭", "folding hand fan"],
    ["🪮", "hair pick"],
    ["🪯", "khanda"],
    ["🫀", "anatomical heart"],
    ["🫁", "lungs"],
    ["🫂", "people hugging"],
    ["🫃", "pregnant man"],
    ["🫄", "pregnant person"],
    ["🫅", "person with crown"],
    ["🫎", "moose"],
    ["🫏", "donkey"],
    ["🌭", "hot dog"],
    ["🌮", "taco"],
    ["🌯", "burrito"],
    ["🍾", "bottle with popping cork"],
    ["🍿", "popcorn"],
    ["🏴", "waving black flag"],
    ["🏸", "badminton racquet and shuttlecock"],
    ["🏹", "bow and arrow"],
    ["🏺", "amphora"],
    ["🏻", "fitzpatrick type-1-2"],
    ["🏼", "fitzpatrick type-3"],
    ["🏽", "fitzpatrick type-4"],
    ["🏾", "fitzpatrick type-5"],
    ["🏿", "fitzpatrick type-6"],
    ["👑", "crown"],
    ["👒", "womans hat"],
    ["👓", "eyeglasses"],
    ["👔", "necktie"],
    ["👕", "t-shirt"],
    ["👖", "jeans"],
    ["👗", "dress"],
    ["👘", "kimono"],
    ["👙", "bikini"],
    ["👚", "womans clothes"],
    ["👛", "purse"],
    ["👜", "handbag"],
    ["👝", "pouch"],
    ["👞", "mans shoe"],
    ["👟", "athletic shoe"],
    ["👠", "high-heeled shoe"],
    ["👡", "womans sandal"],
    ["👢", "womans boots"],
    ["👣", "footprints"],
    ["👤", "bust in silhouette"],
    ["👥", "busts in silhouette"],
    ["💈", "barber pole"],
    ["💉", "syringe"],
    ["💊", "pill"],
    ["💋", "kiss mark"],
    ["💌", "love letter"],
    ["💍", "ring"],
    ["💎", "gem stone"],
    ["💏", "kiss"],
    ["💐", "bouquet"],
    ["💑", "couple with heart"],
    ["💒", "wedding"],
    ["📿", "prayer beads"],
    ["🕋", "kaaba"],
    ["🕌", "mosque"],
    ["🕍", "synagogue"],
    ["🕎", "menorah with nine branches"],
    ["🕺", "man dancing"],
    ["🖕", "reversed hand with middle finger extended"],
    ["🖖", "raised hand with part between middle and ring fingers"],
    ["🖤", "black heart"],
    ["🗻", "mount fuji"],
    ["🗼", "tokyo tower"],
    ["🗽", "statue of liberty"],
    ["🗾", "silhouette of japan"],
    ["🗿", "moyai"],
    ["✅", "white heavy check mark"],
    ["✨", "sparkles"],
    ["❌", "cross mark"],
    ["❎", "negative squared cross mark"],
    ["❓", "black question mark ornament"],
    ["❔", "white question mark ornament"],
    ["❕", "white exclamation mark ornament"],
    ["❗", "heavy exclamation mark symbol"],
    ["➕", "heavy plus sign"],
    ["➖", "heavy minus sign"],
    ["➗", "heavy division sign"],
    ["➰", "curly loop"],
    ["➿", "double curly loop"],
    ["⬛", "black large square"],
    ["⬜", "white large square"],
    ["⭐", "white medium star"],
    ["⭕", "heavy large circle"],
    ["🇦", "regional indicator symbol letter a"]
  ] },
];

export const FREQUENT = ["😂", "😩", "💀", "🚩", "🔥", "😬", "👏", "🫡", "💯", "🤝", "😭", "👀"];
