// ONE place to edit what goes in sitemap.xml and how it is described.
// The sitemap itself is generated by app/sitemap.js (served at /sitemap.xml); robots.txt by app/robots.js.
//
// STATIC_PAGES: pages that always exist. Add or remove paths here.
//   changeFrequency: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never"
//   priority: 0.0 to 1.0 (a hint, not a command; the homepage is 1.0)
export const STATIC_PAGES = [
  { path: "", changeFrequency: "daily", priority: 1 },
  { path: "/layoffs", changeFrequency: "daily", priority: 0.9 },
  { path: "/decoder", changeFrequency: "weekly", priority: 0.9 },
  { path: "/circles", changeFrequency: "weekly", priority: 0.6 },
  { path: "/translator", changeFrequency: "weekly", priority: 0.6 },
  { path: "/title-translator", changeFrequency: "weekly", priority: 0.6 },
  { path: "/companies", changeFrequency: "weekly", priority: 0.6 },
  { path: "/pulse", changeFrequency: "daily", priority: 0.5 },
  { path: "/premium", changeFrequency: "monthly", priority: 0.4 },
  { path: "/terms", changeFrequency: "yearly", priority: 0.3 },
  { path: "/privacy", changeFrequency: "yearly", priority: 0.3 },
];

// Pages added automatically from the database (change the limits or the rules here).
export const DYNAMIC = {
  stories: { limit: 40000, minBodyChars: 200, changeFrequency: "weekly", priority: 0.7 },   // published, not opted out, not high-risk
  companies: { limit: 5000, changeFrequency: "daily", priority: 0.8 },                        // only companies with at least one story
  circles: { limit: 2000, changeFrequency: "weekly", priority: 0.5 },                         // public circles only
  decoder: { changeFrequency: "monthly", priority: 0.6 },                                     // one page per glossary phrase (lib/stories/glossary.js)
};

// Paths that must never appear in the sitemap even if added above by mistake.
export const NEVER_INDEX_PREFIXES = ["/admin", "/api", "/messages", "/settings", "/profile", "/my-stories", "/alerts", "/verify-employment", "/login", "/signup", "/stories/new"];
